version: '2.0'

services:

  mysql:
    build: .
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= '${ROOT_PASSWORD}' 
      - MYSQL_DATABASE= '${DATABASE}'
      - MYSQL_USER= '${SECRET_USER}'
      - MYSQL-PASSWORD= '${SECRET_PASSWORD}'
    restart: always      

      

